name: Deploy Strapi

on:
  push:
    branches:
      - main  # Запускати workflow при пушах до гілки main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Клонування репозиторію
      - name: Checkout repository
        uses: actions/checkout@v3

      # Встановлення SSH-клієнта
      #- name: Install SSH client
      #  run: sudo apt-get update && sudo apt-get install -y sshpass

      # Виконання команд на сервері
      - name: Deploy on server
        env:
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SSH_PORT: ${{ secrets.SSH_PORT }}
        run: |
          sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no -p ${SSH_PORT:-22} $SSH_USERNAME@$SERVER_IP << EOF
          echo "Stopping NextJS application..."
          echo "$SSH_PASSWORD" | sudo -S systemctl stop nextjs

          cd /home/max/simpatik.group || exit

          echo "Stashing local changes..."
          git stash

          echo "Pulling latest version from Git..."
          git pull

          echo "Installing dependencies..."
          npm install -y

          echo "Building project..."
          npm run build

          echo "Starting NextJS application..."
          echo "$SSH_PASSWORD" | sudo -S systemctl start nextjs

          echo "Deployment completed successfully!"
          EOF
